-- migration: 20251014120000_fix_pk_movie_availability_user_platform.sql
-- description: introduce surrogate primary keys for movie_availability and user_platform

-- NOTE: This migration adjusts primary keys to use surrogate IDs while preserving
--       uniqueness of the original composite keys via unique constraints.

-- 1) movie_availability: drop composite PK (tconst, platform_id), add id identity PK
alter table "public"."movie_availability" drop constraint if exists "movie_availability_pkey";

alter table "public"."movie_availability"
    add column if not exists "id" bigint generated by default as identity;

-- set new primary key on id
alter table "public"."movie_availability"
    add constraint "movie_availability_pkey" primary key ("id");

-- enforce uniqueness of the original pair
do $$
begin
    if not exists (
        select 1
        from pg_constraint c
        join pg_namespace n on n.oid = c.connamespace
        where c.conname = 'movie_availability_tconst_platform_key'
          and n.nspname = 'public'
    ) then
        alter table "public"."movie_availability"
            add constraint "movie_availability_tconst_platform_key" unique ("tconst", "platform_id");
    end if;
end $$;


-- 2) user_platform: drop composite PK (user_id, platform_id), add id identity PK
alter table "public"."user_platform" drop constraint if exists "user_platform_pkey";

alter table "public"."user_platform"
    add column if not exists "id" bigint generated by default as identity;

-- set new primary key on id
alter table "public"."user_platform"
    add constraint "user_platform_pkey" primary key ("id");

-- enforce uniqueness of the original pair
do $$
begin
    if not exists (
        select 1
        from pg_constraint c
        join pg_namespace n on n.oid = c.connamespace
        where c.conname = 'user_platform_user_id_platform_id_key'
          and n.nspname = 'public'
    ) then
        alter table "public"."user_platform"
            add constraint "user_platform_user_id_platform_id_key" unique ("user_id", "platform_id");
    end if;
end $$;


